# Generated by Django 5.2.1 on 2025-05-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='version',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
