# Generated by Django 5.2.1 on 2025-05-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
